// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgHelperApp.Model.Data;

namespace ProgHelperApp.Migrations
{
    [DbContext(typeof(AplicationContext))]
    [Migration("20230430112308_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProgHelperApp.Model.CardProject", b =>
                {
                    b.Property<Guid>("id_CardProject_F")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBegining_F")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid?>("Employeeid_Employee_F")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid>("id_ProjectManager_F")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id_CardProject_F");

                    b.HasIndex("Employeeid_Employee_F");

                    b.ToTable("CardProjects");
                });

            modelBuilder.Entity("ProgHelperApp.Model.Employee", b =>
                {
                    b.Property<Guid>("id_Employee_F")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Patronymic_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Phone_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerName_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("id_Employee_F");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ProgHelperApp.Model.Task", b =>
                {
                    b.Property<Guid>("id_Task_F")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deadline_F")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Status_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title_F")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("id_Task_F");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ProgHelperApp.Model.CardProject", b =>
                {
                    b.HasOne("ProgHelperApp.Model.Employee", "Employee")
                        .WithMany("CardProjects")
                        .HasForeignKey("Employeeid_Employee_F");
                });
#pragma warning restore 612, 618
        }
    }
}
